[JENKINS-66132] - Update the parent pom from 4.12 to 4.19
jenkinsci/publish-over-ssh-plugin pull request #40
Opened 2021-07-14 00:35 UTC by Onyimatics

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- Update the parent pom from `4.12` to `4.19`
- [x] Link to relevant issues in GitHub or Jira
- [JENKINS-66132](https://issues.jenkins.io/browse/JENKINS-66132)

@MarkEWaite @oleg-nenashev

2021-07-14 05:53 UTC, MarkEWaite requested changes

2021-07-14 06:10 UTC, Onyimatics commented on pom.xml.versionsBackup
> +<?xml version="1.0" encoding="UTF-8"?>
Alright, I will go ahead and remove it. Thanks @MarkEWaite

2021-07-14 14:29 UTC, MarkEWaite approved these changes

2021-07-17 17:57 UTC, timja approved these changes

2021-07-17 17:58 UTC, merged